UPLOADFILES:
  hooks:
    REPEAT: '?'

METADATA:
  tester_type: sql
  tester_name:
    TEXT_MATCHER: .+
  script_data:
    REPEAT+:
      runnable_group:
        REPEAT+:
          script_file_path: 
            TEXT_MATCHER: .+
          dataset_file_path:
            TEXT_MATCHER: .*
          order_on:
            TEXT_MATCHER: .*
          points:
            TEXT_MATCHER: \d+
            DEFAULT: '1'
      enable_feedback_file_hook:
        OPTIONS:
          - true
          - false 
      feedback_file:
        TEXT_MATCHER: .*
      script_timeout:
        TEXT_MATCHER: \d+
        DEFAULT: "30"
      hooks_file_path:
        TEXT_MATCHER: .*
      schema_name:
        TEXT_MATCHER: .*
        